# test
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: dansam
    password: qwer1234
  jpa:
    hibernate :
      ddl-auto : create
    show-sql : true
    properties :
      hibernate :
        dialect : org.hibernate.dialect.H2Dialect

custom:
  property:
    single: test-property

logging :
  config : classpath:logback-spring-test.xml