# Mybatis
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/demo_schema
#    username: demo__user
#    password: qwer1234
#
#mybatis:
#  mapper-locations: "classpath:mybatis.mappers/*.xml"
#  configuration:
#    map-underscore-to-camel-case: true

# 속성값 및 로깅 레벨 설정
#custom:
#  property:
#    single: custom-property
#    comlist: comma,sparated,list,to,value
#    ncp:
#      id: api-id
#      key: api-key
#      url: https://ncp.com/
#logging :
#  level :
#    root : info
#    dev.projectlion.demo.week7 : debug
spring :
  profiles :
    active : test
management :
  endpoints :
    enabled-by-default : false
    web:
      exposure:
        include : health,info,loggers,shutdown,prometheus
  endpoint:
    health:
      show-details : always
      show-components : always
      enabled : true
    info:
      enabled : true
    loggers:
      enabled : true
    shutdown:
      enabled : true
    prometheus :
      enabled : true