# local
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_jpa_schema
    username: demo_jpa_user
    password: qwer1234
  jpa:
    hibernate :
      ddl-auto : create-drop # 개발 과정에서는 create 또는 create-drop
    show-sql : true
    properties :
      hibernate :
        dialect : org.hibernate.dialect.MySQL8Dialect
