server :
  port : 8081

spring :
  config :
    activate :
      on-profile : local

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,loggers,shutdown
  endpoint:
    health:
      show-details: always
      show-components: always
